apiVersion: v1
kind: ConfigMap
metadata:
  name: ocean-sensor-config
  labels:
    app: ocean-sensor
data:
  BINDPLANE_HOST: "192.168.1.190"
  BINDPLANE_HTTP_PORT: "4317"
  BINDPLANE_GRPC_PORT: "4318"
  BINDPLANE_SERVICE_NAME: "ocean-sensor"
  SIMULATOR_BUOY_COUNT: "300"
