apiVersion: v1
kind: Service
metadata:
  name: ocean-sensor
  labels:
    app: ocean-sensor
spec:
  selector:
    app: ocean-sensor
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
